import {
  GraduationCap,
  Users,
  ClipboardList,
  FileText,
  ImageIcon,
  MessageSquareHeart,
  Settings,
  Menu,
  ShieldCheck,
  Briefcase,
  Palette,
} from "lucide-react";
import { Resource, ResourceKey, QueryParamsState } from "../types/admin.types";

export const API_URL = (process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:5000/api/v1").replace(/\/$/, "");

export const resourcePath: Record<ResourceKey, string> = {
  students: "students",
  staff: "staff",
  inquiries: "inquiries",
  news: "news",
  // notices: "notices",
  gallery: "gallery",
  reviews: "reviews",
  "school-settings": "school-settings",
  "menu-items": "menu-items",
  pages: "pages",
  users: "auth/users",
  careers: "careers",
  theme: "theme",
};

export const resources: Resource[] = [
  {
    key: "students",
    label: "Students",
    description: "Admissions and student records",
    icon: GraduationCap,
    protected: true,
    fields: ["name", "grade", "section", "parentName", "parentEmail", "status", "createdAt", "updatedAt"],
    inputs: { name: "text", grade: "text", section: "text", dob: "date", gender: "select", parentName: "text", parentPhone: "text", parentEmail: "text", address: "textarea", status: "select", avatar: "file" },
    options: { gender: ["Male", "Female", "Other"], status: ["Active", "Inactive"] },
  },
  {
    key: "staff",
    label: "Staff",
    description: "Faculty and employee directory",
    icon: Users,
    protected: true,
    fields: ["name", "designation", "department", "email", "status", "createdAt", "updatedAt"],
    inputs: { name: "text", email: "text", phone: "text", department: "text", staffType: "select", designation: "text", qualification: "text", joinDate: "date", status: "select", avatar: "file" },
    options: { staffType: ["Teaching", "Non-Teaching", "Administrative", "Support Staff", "Management"], status: ["Active", "On Leave", "Inactive"] },
  },
  {
    key: "inquiries",
    label: "Enquiries",
    description: "Admission and contact leads",
    icon: ClipboardList,
    protected: true,
    fields: ["name", "inquiryType", "email", "contact", "status", "createdAt", "updatedAt"],
    inputs: {
      name: "text",
      contact: "text",
      email: "text",
      inquiryType: "select",
      message: "textarea",
      status: "select",
    },
    options: { inquiryType: ["Admission", "General", "Academic", "Transport", "Fee Structure", "Other"], status: ["Pending", "In Progress", "Resolved", "Closed"] },
  },
  {
    key: "news",
    label: "News",
    description: "Homepage announcements",
    icon: FileText,
    protected: true,
    fields: ["title", "redirectUrl", "createdAt", "updatedAt"],
    inputs: { title: "text", redirectUrl: "text", attachmentUrl: "file" },
  },
  {
    key: "gallery",
    label: "Gallery",
    description: "Campus media library, albums and directory folders",
    icon: ImageIcon,
    protected: true,
    fields: ["eventName", "directory", "eventType", "fileUrl", "createdAt", "updatedAt"],
    inputs: { eventName: "text", directory: "select", eventType: "select", fileUrl: "file" },
    options: {
      directory: [
        "Album",
        "Album/Events",
        "Album/Hostel",
        "Album/Infrastructure",
        "Album/Empowerment",
        "Album/Competitions",
        "Album/Partners",
        "Album/Achievements",
        "Album/Reviews",
        "Album/Awareness",
        "PressRelease",
        "Settings/Logos",
        "Settings/Home",
        "Documents/General",
        "Documents/Admission",
        "Student",
        "Staff",
        "Videos",
      ],
      eventType: [
        "General",
        "Events",
        "Hostel",
        "Empowerment",
        "Competitions",
        "Partners",
        "Achievements",
        "Reviews",
        "Awareness",
        "PressRelease",
        "Documents",
        "Settings",
        "Home",
        "Logos",
        "Infrastructure",
        "Student",
        "Staff",
        "Videos",
      ],
    },
  },
  {
    key: "reviews",
    label: "Reviews",
    description: "Testimonials moderation",
    icon: MessageSquareHeart,
    protected: true,
    fields: ["name", "batch", "rating", "isApproved", "createdAt", "updatedAt"],
    inputs: { name: "text", batch: "text", rating: "number", feedback: "textarea", avatar: "file", isApproved: "boolean" },
  },
  {
    key: "school-settings",
    label: "Settings",
    description: "School identity and configuration",
    icon: Settings,
    protected: true,
    fields: ["key", "category", "value", "status", "isPublic", "createdAt", "updatedAt"],
    inputs: { key: "text", category: "select", value: "textarea", description: "textarea", status: "select", isPublic: "boolean" },
    options: { category: ["Content", "Header", "Footer", "General"], status: ["Active", "Inactive"] },
  },
  {
    key: "menu-items",
    label: "Website menu",
    description: "Navigation structure (up to 3 levels)",
    icon: Menu,
    fields: ["title", "level", "parentId", "category", "isPublished", "order", "createdAt", "updatedAt"],
    inputs: { title: "text", parentId: "select", targetUrl: "text", order: "number", isPublished: "boolean" },
    options: { category: ["Header", "Footer", "Quick Links", "Sidebar"] },
  },
  {
    key: "pages",
    label: "Pages",
    description: "Manage dynamic pages & rich text content",
    icon: FileText,
    protected: true,
    fields: ["title", "targetUrl", "isPublished", "createdAt", "updatedAt"],
    inputs: { title: "text", targetUrl: "text", textContent: "richtext", isPublished: "boolean" },
  },
  {
    key: "users",
    label: "Administrators",
    description: "Authorised user accounts",
    icon: ShieldCheck,
    protected: true,
    fields: ["name", "email", "role", "status", "createdAt", "updatedAt"],
    inputs: { name: "text", email: "text", password: "text", role: "text", status: "select" },
    options: { status: ["ACTIVE", "INACTIVE", "SUSPENDED"] },
  },
  {
    key: "careers",
    label: "Careers",
    description: "Manage job openings, dynamic table fields, and candidate applications",
    icon: Briefcase,
    protected: true,
    fields: ["title", "qualification", "isActive", "createdAt"],
    inputs: { title: "text", qualification: "text", image: "file", description: "textarea", isActive: "boolean" },
  },
  {
    key: "theme",
    label: "Theme & Appearance",
    description: "Public web theme studio, color palettes, and visual customization",
    icon: Palette,
    protected: true,
    fields: ["name", "slug", "isActive", "isPreset", "createdAt"],
    inputs: { name: "text", description: "textarea", isActive: "boolean" },
  },
];

export const OPTIONAL_FIELDS = new Set([
  "avatar",
  "attachmentUrl",
  "fileUrl",
  "file",
  "description",
  "expiryDate",
  "house",
  "transportRoute",
  "altText",
  "menuId",
  "redirectUrl",
  "targetUrl",
  "parentId",
  "textContent",
  "isPublic",
  "isPublished",
  "isApproved",
]);

export const sectionNames = ["Overview", "People", "Content", "System"] as const;

export const resourceSections: Record<ResourceKey, (typeof sectionNames)[number]> = {
  students: "People",
  staff: "People",
  inquiries: "People",
  news: "Content",
  gallery: "Content",
  reviews: "Content",
  "menu-items": "Content",
  pages: "Content",
  "school-settings": "System",
  users: "System",
  careers: "People",
  theme: "System",
};

export const DEFAULT_QUERY: QueryParamsState = {
  page: 1,
  limit: 8,
  search: "",
  sortBy: "createdAt",
  sortOrder: "desc",
  filterKey: "",
  filterValue: "All",
};
