export const TEXT_COLORS = [
  { name: "Dark Slate", value: "#1e293b" },
  { name: "School Blue", value: "#1a5d9c" },
  { name: "Sky Blue", value: "#0284c7" },
  { name: "Emerald Green", value: "#059669" },
  { name: "Amber Gold", value: "#d97706" },
  { name: "Crimson Red", value: "#dc2626" },
  { name: "Royal Purple", value: "#7c3aed" },
  { name: "Muted Gray", value: "#64748b" },
];

export const HIGHLIGHT_COLORS = [
  { name: "Clear / Transparent", value: "transparent" },
  { name: "Yellow Highlight", value: "#fef08a" },
  { name: "Green Highlight", value: "#bbf7d0" },
  { name: "Blue Highlight", value: "#bfdbfe" },
  { name: "Pink Highlight", value: "#fbcfe8" },
  { name: "Orange Highlight", value: "#fed7aa" },
  { name: "Light Gray", value: "#e2e8f0" },
];

import {
  Link as LinkIcon,
  Table,
  FileText,
  FileSpreadsheet,
  MousePointerClick,
  ExternalLink,
  LayoutTemplate,
  Sliders,
  Award,
  UserCheck,
  LayoutGrid,
  PhoneCall,
  MessageSquareQuote,
  Info,
  CheckCircle2,
  AlertTriangle,
} from "lucide-react";

export const TOOLBOX_COMPONENTS = [
  {
    id: "frameCard",
    title: "Image Frame & Card Studio",
    subtitle: "Portrait badge card, floating accent & polaroid templates",
    icon: LayoutTemplate,
    color: "bg-amber-600 text-white",
  },
  {
    id: "hyperlink",
    title: "Hyperlink & Action Button",
    subtitle: "Write text with link & button style",
    icon: LinkIcon,
    color: "bg-sky-600 text-white",
  },
  {
    id: "customTable",
    title: "Data Table & CSV Importer",
    subtitle: "Build custom HTML grid or import CSV data",
    icon: Table,
    color: "bg-[#102a4c] text-white",
  },
  {
    id: "wordCard",
    title: "Word / Google Doc Card",
    subtitle: "Embed Word (.docx) or Google Doc card",
    icon: FileText,
    color: "bg-blue-700 text-white",
  },
  {
    id: "excelCard",
    title: "Excel / Google Sheet Card",
    subtitle: "Embed Excel (.xlsx) or Google Sheet card",
    icon: FileSpreadsheet,
    color: "bg-emerald-700 text-white",
  },
  {
    id: "pdfCard",
    title: "PDF Document Studio Card",
    subtitle: "Customize & embed PDF preview card",
    icon: FileText,
    color: "bg-rose-600 text-white",
  },
  {
    id: "ctaBanner",
    title: "Call-to-Action Link Banner",
    subtitle: "Header, paragraph & redirect button",
    icon: MousePointerClick,
    color: "bg-blue-700 text-white",
  },
  {
    id: "quickLinksGrid",
    title: "Quick Redirect Links Grid",
    subtitle: "3 hyperlinked navigation cards",
    icon: ExternalLink,
    color: "bg-[#102a4c] text-white",
  },
  {
    id: "hero",
    title: "Hero Banner Section",
    subtitle: "Navy Header, Badge & Buttons",
    icon: LayoutTemplate,
    color: "bg-blue-600 text-white",
  },
  {
    id: "slider",
    title: "Image Banner Slider",
    subtitle: "Full Width Campus Image",
    icon: Sliders,
    color: "bg-indigo-600 text-white",
  },
  {
    id: "features",
    title: "3-Column Feature Cards",
    subtitle: "Academic, Sports & Safety",
    icon: Award,
    color: "bg-emerald-600 text-white",
  },
  {
    id: "principal",
    title: "Principal Note Card",
    subtitle: "Photo Frame & Quote Box",
    icon: UserCheck,
    color: "bg-amber-600 text-white",
  },
  {
    id: "stats",
    title: "School Stat Counters",
    subtitle: "4 Metric Stat Blocks",
    icon: LayoutGrid,
    color: "bg-violet-600 text-white",
  },
  {
    id: "contact",
    title: "Contact Info Box",
    subtitle: "Address, Phone & Hours",
    icon: PhoneCall,
    color: "bg-cyan-600 text-white",
  },
  {
    id: "testimonials",
    title: "Testimonial Reviews",
    subtitle: "Parent & Student Stars",
    icon: MessageSquareQuote,
    color: "bg-rose-600 text-white",
  },
  {
    id: "disclosureTable",
    title: "CBSE Disclosure Table",
    subtitle: "Document Download Grid",
    icon: FileSpreadsheet,
    iconColor: "text-blue-600",
    color: "bg-slate-700 text-white",
  },
  {
    id: "info",
    title: "Blue Notice Box",
    subtitle: "Information Callout",
    icon: Info,
    color: "bg-sky-500 text-white",
  },
  {
    id: "success",
    title: "Green Success Note",
    subtitle: "Positive Achievement Box",
    icon: CheckCircle2,
    color: "bg-green-600 text-white",
  },
  {
    id: "warning",
    title: "Amber Alert Box",
    subtitle: "Warning / Deadline Box",
    icon: AlertTriangle,
    color: "bg-amber-500 text-white",
  },
  {
    id: "grid",
    title: "2-Column Grid Layout",
    subtitle: "Side-by-side Columns",
    icon: LayoutGrid,
    color: "bg-purple-600 text-white",
  },
];

